Version 4
SymbolType BLOCK
RECTANGLE Normal -48 -40 64 40
WINDOW 0 8 -40 Bottom 2
WINDOW 3 8 40 Top 2
SYMATTR Prefix X
SYMATTR Value SN74AHCT1G14
SYMATTR ModelFile C:\Users\osbor\Desktop\buck-converter-stability\ltspice\clock_isolator\SN74AHCT1G14.SUB
PIN -48 -16 LEFT 8
PINATTR PinName Y
PINATTR SpiceOrder 1
PIN -48 16 LEFT 8
PINATTR PinName A
PINATTR SpiceOrder 2
PIN 64 -16 RIGHT 8
PINATTR PinName VCC
PINATTR SpiceOrder 3
PIN 64 16 RIGHT 8
PINATTR PinName AGND
PINATTR SpiceOrder 4
